### ISSUE TITLE
[New Feature]: Introduce a bal tool to support consolidating multiple services into a single executable

### ISSUE THREAD

**Issue by azinneera** [ballerina-platform/ballerina-spec#1331]
### Description

Ballerina inherently supports microservices-style deployments, which are well-suited for microservice orchestration platforms like Kubernetes. However, many enterprise users deploy on VMs or Docker, where managing each service as a separate process increases complexity and resource overhead. We must provide a solution tailored to such scenarios by enabling consolidated deployments.

### Describe your problem(s)

For users who follow a monolith-style deployment, the following must be supported OOTB:

- Allow multiple services to run as a single runtime process.
- Facilitate easy deployment in Docker-based and VM environments.
- Provide intuitive configuration through CLI options or a configuration file.

### Describe your solution(s)

The goal is to allow developers to specify services to consolidate into a single runtime process. For this, we will introduce a bal tool to generate the code required to group multiple services into one deployable artifact. 

The tool:
* Parses the `Ballerina.toml` file to identify the services to consolidate
* Generates the `consolidated.bal` file with the shared listener and the service packages imported.
* Builds a single deployment artifact (e.g., .jar or Docker image) containing all the services and a `Config.toml` containing all configurable variables.

**Features**

- Developers can create a consolidated package using the below command:
   `bal new -t ballerina/consolidate myConsolidatedPkg`

    This command creates a new Ballerina package with the consolidate tool added in the `Ballerina.toml` file as follows:
    ```toml
    [package]
    org = "myOrg"
    name = "myConsolidatedPkg"
    version = "0.1.0"

    [[tool.consolidate]]
    id = "consolidate1"
    options.services = ["myOrg/svc1", "myOrg/svc2"]  # modify the values with the services to consolidate
    ```
- Developers can Generate a single deployment artifact by executing the below command:
   `bal build [--cloud]`

A few other name suggestion for the tool:

<meta charset="utf-8"><div>
Suggested name | Ballerina.toml syntax
-- | --
merge | [[tool.merge]]
bundle | [[tool.bundle]]
integrate | [[tool.integrate]]

</div></b>

### Related area

-> Compilation
