### ISSUE TITLE
Add inline tables support to the toml parser

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-spec#692]
**Description:**
Inline table should be able to read as a table arrays.
```toml
[[platform.java11.dependency]]
path = "/user/sameera/libs/toml4j.jar"
artifactId = "toml4j"
version = "0.7.2"
groupId = "com.moandjiezana.toml"

[platform.java11]
dependency = [{path = "/user/sameera/libs/toml4j.jar", artifactId = "toml4j", version = "0.7.2", groupId = "com.moandjiezana.toml"}]
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**
