### ISSUE TITLE
Need TOML spec support for map type configurable variables

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-spec#709]
**Description:**
As per the design of #41, we allow providing values for `configurable` variables through a TOML file (`Config.toml`). 
We currently support the ballerina types int, float, boolean, string, decimal and the arrays of these.

We came across a requirement from module-ballerina-auth where a predefined TOML structure is used to configure values in a map. 
Eg: [BBE](https://ballerina.io/learn/by-example/secured-service-with-basic-auth.html) 

The `configurable` specifies a predefined structure (TOML table) to indicate the module name  in order to differentiate variables from multiple modules as follows, 

```toml
[packagName]
variableName = "variableValue"

```
The structure we previously used in the basic Authentication feature (in auth module) is as follows,
```toml
  [b7a.users]

  [b7a.users.alice]
  password="password1"
  scopes="scope1"

  [b7a.users.bob]
  password="password2"
  scopes="scope2,scope3"
```
To generalize this requirement, we need to find a TOML structure for the map types that includes the module details as well. 

**Suggested Labels:**

   
**Code sample that shows issue:**
To represent a single record defined here
```ballerina
public type AuthInfo record {|
   string password = "";
   string scopes = "";
|};

configurable map<AuthInfo> & readonly users = ?;
```
could this TOML structure be adequate?

```
  [auth.users]

  [auth.users.alice]
  password="password1"
  scopes="scope1"

  [auth.users.bob]
  password="password2"
  scopes="scope2,scope3"
```

**Related Issues:**
https://github.com/ballerina-platform/ballerina-standard-library/issues/862

**Comment by manuranga** [comment]
@hasithaa @sameerajayasoma  @sanjiva please note that we'll start implementing this for the next release because it has become a requirement for auth stdlib.

**Comment by sameerajayasoma** [comment]
There is a potential problem with mapping values and submodule names. This point was addressed in the initial `configurable` design done by @jclark. Here are the possibilities specified in that design doc. 

> 1. Don't support mapping values for configuration items in TOML; you can always use a Ballerina table, which will be mapped onto a json array.
> 2. Interpret something as a submodule if there is a module of that name in the program and otherwise as a mapping value. The linker could potentially catch ambiguities (i.e. a configurable item with the same name as a submodule).
> 3. Use [a.b.c] for submodules and a = { b = 1 } for values, and
> don't treat them as equivalent (even though TOML says they are), or
> give a warning when this usage is not followed

We should go ahead with option #2 IMO. With this, say you have two modules named `x.y` and `x.y.z`. You can't have a `configurable` variable called `z` in module `x.y`. This restriction applies to any `configurable` variable type, not just for mapping values. The current implementation does not handle this at the moment. @HindujaB, please note. 

The suggested TOML syntax looks good.
```toml
# 1) Inline table version
[auth.users]
alice = { password ="password1", scopes="scope1"}

# 2) Standard table version
[auth.users.alice]
password="password1"
scopes="scope1"
```

However, I would use an array of `AuthInfo` instead of a map for this use case.  I will discuss this in the original issue.
