### ISSUE TITLE
Record ballerina dist short version in manifest for application packages

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/ballerina-spec#954]
**Description:**
Need to add ballerina distribution short version to the Ballerina.toml under platform section of application packages sames we add it to library packages.

Ballerina.toml:
```toml
[package]
distribution = "slbeta3"

[build-options]
observabilityIncluded = true
```

**Suggested Labels:**

   
**Code sample that shows issue:**

**Related Issues:**
