### ISSUE TITLE
Introduce `description` field to the `[package]` section in `Ballerina.toml`

### ISSUE THREAD

**Issue by sameerajayasoma** [ballerina-platform/ballerina-spec#982]
Currently, the short description of the package displayed in Ballerina central is extracted from the `Package.md`. I think that design is suboptimal. 

With the description filed, package authors have a clear approach to providing a short description of a package.

**Comment by hevayo** [comment]
To capture the summary one approach is to use front-matter jekyll

```
---
summary: Blogging Like a Hacker
---

#Module Md Content
```

**Comment by sameerajayasoma** [comment]
> +1 for the suggestion, I also think it will be a cleaner approach.
> 
> For module summary we extract the summary from Module.md if so there is bit of an inconsistency.

How about adding the capability to specify module-specific metadata in `Ballerina.toml`? Here is roughly what I am thinking. 

```toml 
[package]
org = "samjs"
name = "mylib"
version = "0.1.0"
description = ""
distribution = "2201.8.2"

[package.module.foo]
description = ""

[package.module.bar]
description = ""
```
